export const MONGO_CLIENT = 'MONGO_CLIENT';
export const DATABASE_USER = 'DATABASE_USER';
export const DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const DATABASE_NAME = 'DATABASE_NAME';
export const DATABASE_COLLECTION_TODO = 'Todo';
